#!/usr/bin/env bash
# vim: set ft=sh

set -euo pipefail

exec 3>&1
exec 1>&2

cd "${1}"

payload=$(mktemp /tmp/resource.XXXXXX)
cat > "${payload}" <&0

# source
bitbucket_type="$(jq -r '.source.bitbucket_type // "server"' < "${payload}")"
base_url="$(jq -r '.source.base_url // ""' < "${payload}")"
username="$(jq -r '.source.username // ""' < "${payload}")"
password="$(jq -r '.source.password // ""' < "${payload}")"
project="$(jq -r '.source.project // ""' < "${payload}")"
repository="$(jq -r '.source.repository // ""' < "${payload}")"
git="$(jq -r '.source.git // ""' < "${payload}")"
oauth_id=$(jq -r '.source.oauth_id // ""' < ${payload})
oauth_secret=$(jq -r '.source.oauth_secret // ""' < ${payload})
# params
skip_download="$(jq -r '.params.skip_download // false' < "${payload}")"
fetch_upstream="$(jq -r '.params.fetch_upstream // false' < "${payload}")"
git_params="$(jq -r '.params | del(.skip_download) | del(.fetch_upstream) // {}' < "${payload}")"
# version
version="$(jq -r '.version' < "${payload}")"
version_id="$(jq -r '.version.id' < "${payload}")"

if [[ -z "${base_url}" ]]; then
    echo "error: source.base_url can't be empty"
    exit 1
fi
if [[ -z "${project}" ]]; then
    echo "error: source.project can't be empty"
    exit 1
fi
if [[ -z "${repository}" ]]; then
    echo "error: source.repository can't be empty"
    exit 1
fi
if [[ -z "${git}" ]]; then
    echo "error: source.git can't be empty"
    exit 1
fi

authentication=(-u ${username}:${password})
if [[ -n "${oauth_id}" ]]; then
    oauth_response=$(mktemp /tmp/resource.XXXXXX)
    uri="${base_url}/site/oauth2/access_token"
    curl -XPOST -sSL --fail -u "${oauth_id}:${oauth_secret}" -d grant_type=client_credentials $uri | jq -r '.access_token' > "${oauth_response}"
    authentication=(-H "Authorization: Bearer `cat $oauth_response`")
fi

if [[ "$bitbucket_type" == "server" ]]; then
    uri="${base_url}/rest/api/1.0/projects/${project}/repos/${repository}/pull-requests/${version_id}"
elif [[ "$bitbucket_type" == "cloud" ]]; then
    uri="${base_url}/api/2.0/repositories/${project}/${repository}/pullrequests/${version_id}"
fi

pr=$(mktemp /tmp/resource.XXXXXX)
curl -sL --fail "${authentication[@]}" "${uri}" > "${pr}"

git_payload=$(echo "${git}" | jq --argjson version "${version}" --argjson params "${git_params}" '
    {source: (. * {branch: $version.branch})} + {version: {ref: $version.commit}} + {params: $params}
')

if [[ "${fetch_upstream}" != "false" ]]; then
    if [[ "$bitbucket_type" == "server" ]]; then
        git_payload=$(echo "${git_payload}" | jq --slurpfile pr "${pr}" '
            . * { params: { fetch: [ $pr[0].toRef.id|ltrimstr("refs/heads/") ] } }
        ')
    elif [[ "$bitbucket_type" == "cloud" ]]; then
        git_payload=$(echo "${git_payload}" | jq --slurpfile pr "${pr}" '
            . * { params: { fetch: [ $pr[0].destination.branch.name|ltrimstr("refs/heads/") ] } }
        ')
    fi
fi

resource_path="${@%/}"
if [[ "${skip_download}" = "false" ]]; then
    echo "$git_payload" | /opt/git-resource/in "${resource_path}"
else
    mkdir -p ${resource_path}/.git/info
fi

# exclude pull-request-info from git index
echo "pull-request-info" > ${resource_path}/.git/info/exclude

# Bitbucket Cloud and (self-hosted) Server APIs are a bit different
if [[ "$bitbucket_type" == "server" ]]; then
    jq -n --argjson version "${version}" --slurpfile pr "${pr}" '{
            id: $pr[0].id,
            description: $pr[0].description,
            author: {
                name: $pr[0].author.user.name,
                email: $pr[0].author.user.emailAddress,
                fullname: $pr[0].author.user.displayName,
            },
            commit: $version.commit,
            feature_branch: $version.branch,
            title: $pr[0].title,
            upstream_branch: $pr[0].toRef.id,
            url: $pr[0].links.self[0].href,
            updated_at: $version.updated_at
        }' > pull-request-info

    cp pull-request-info .git/pr

    jq -n --argjson version "${version}" --slurpfile pr "${pr}" '{
            version: $version,
            metadata: [
                {name: "url", value: $pr[0].links.self[0].href},
                {name: "author", value: $pr[0].author.user.displayName},
                {name: "commit", value: $version.commit},
                {name: "feature-branch", value: $version.branch},
                {name: "upstream-branch", value: $pr[0].toRef.id}
            ]
        }' >&3
elif [[ "$bitbucket_type" == "cloud" ]]; then
    jq -n --argjson version "${version}" --slurpfile pr "${pr}" '{
            id: $pr[0].id,
            description: $pr[0].description,
            author: {
                name: $pr[0].author.username,
                fullname: $pr[0].author.display_name,
            },
            commit: $version.commit,
            feature_branch: $version.branch,
            title: $pr[0].title,
            upstream_branch: $pr[0].destination.branch.name,
            url: $pr[0].links.html.href,
            updated_at: $pr[0].created_on
        }' > pull-request-info

    cp pull-request-info .git/pr

    jq -n --argjson version "${version}" --slurpfile pr "${pr}" '{
            version: $version,
            metadata: [
                {name: "title", value: $pr[0].title},
                {name: "url", value: $pr[0].links.html.href},
                {name: "author", value: $pr[0].author.display_name},
                {name: "commit", value: $version.commit},
                {name: "feature-branch", value: $version.branch},
                {name: "upstream-branch", value: $pr[0].destination.branch.name},
                {name: "pullrequest updated", value: $pr[0].updated_on}
            ]
        }' >&3
fi
