#!/usr/bin/env bash
# vim: set ft=sh

set -euo pipefail

exec 3>&1
exec 1>&2

cd "${1}"

payload=$(mktemp /tmp/resource.XXXXXX)
cat > "${payload}" <&0

# source
bitbucket_type=$(jq -r '.source.bitbucket_type // "server"' < "${payload}")
base_url=$(jq -r '.source.base_url // ""' < "${payload}")
username=$(jq -r '.source.username // ""' < "${payload}")
password=$(jq -r '.source.password // ""' < "${payload}")
project=$(jq -r '.source.project // ""' < "${payload}")
repository=$(jq -r '.source.repository // ""' < "${payload}")
path=$(jq -r '.params.repository // .source.dir // .source.repository // ""' < "${payload}")
params=$(jq -rc '.params' < "${payload}")
action=$(jq -rc '.action // ""' <<< "${params}")

path="$(realpath "${PWD}"/"${path}")/"
pr=$(cat "${path}.git/pr")

eval_param() {
    eval echo "$(jq -r "${1}" <<< "${params}")"
}

change_build_status() {
    if [[ -z "${base_url}" ]]; then
        echo "error: source.base_url can't be empty"
        exit 1
    fi

    commit=$(jq -r '.commit' <<< "${pr}")

    if [[ "${bitbucket_type}" == "server" ]]; then
        url="${base_url}/rest/build-status/1.0/commits/${commit}"
    elif [[ "${bitbucket_type}" == "cloud" ]]; then
        url="${base_url}/api/2.0/repositories/${project}/${repository}/commit/${commit}/statuses/build"
    else
        echo "error: incorrect bitbucket server type '${bitbucket_type}'"
        exit 1
    fi

    change_build_status_payload=$(jq -n \
        --argjson params "${params}" \
        --arg key "$(eval_param '.key // ""')" \
        --arg name "$(eval_param '.name // ""')" \
        --arg description "$(eval_param '.description // ""')" \
        '{
            state: $params.state,
            key: (if $key != "" then $key else $name end),
            name: ((if $key != "" then $key else $name end) + "-" + env.BUILD_ID),
            url: (
                $params.url // (
                    "\(env.ATC_EXTERNAL_URL)/builds/\(env.BUILD_ID)"
                )
            ),
            description: $description|tostring
        }'
    )

    curl -s --fail \
        -u "${username}:${password}" \
        -H "Content-Type: application/json" \
        -XPOST "${url}" \
        -d "${change_build_status_payload}"

    jq -n --argjson pr "${pr}" '{
        version: {
            id: $pr.id|tostring,
            title: $pr.title,
            branch: $pr.feature_branch,
            commit: $pr.commit
        }
    }' >&3
}

push() {
    git=$(jq -r '.source.git // ""' < "${payload}")

    git_payload=$(jq -nc \
        --argjson git "${git}" \
        --argjson pr "${pr}" \
        --arg repository "${path}" '
        {
            source: (
                $git * {
                    branch: $pr.feature_branch
                }
            ),
            params: {
                repository: $repository 
            }
        }
    ')

    git_payload_out=$(/opt/git-resource/out "${1}" <<< "${git_payload}")
 
    jq -n --argjson pr "${pr}" --argjson git "${git_payload_out}" \
        '{
            version: {
                id: $pr.id|tostring,
                title: $pr.title,
                branch: $pr.feature_branch,
                commit: $git.version.ref
            },
            metadata: $git.metadata
        }' >&3
}

case "${action}" in
    # case for backward compatibility
    "")
        echo "warning: please setup the \`action\` parameter"
        change_build_status
    ;;

    "change-build-status")
        change_build_status
    ;;

    "push")
        push "${@%/}"
    ;;

    *)
        echo "error: incorrect params.action (${action})"
        exit 1
    ;;
esac
