resources:
- name: source
  type: git
  source:
    uri: https://github.com/zarplata/concourse-git-bitbucket-pr-resource.git 
    branch: master
    paths:
    - assets
    - Dockerfile

- name: docker-hub
  type: docker-image
  source:
    repository: zarplata/concourse-git-bitbucket-pr-resource
    username: ((docker-hub.username))
    password: ((docker-hub.password))
    tag: latest

jobs:
- name: release-docker-image
  public: true
  serial: true
  plan:
  - get: source
    trigger: true
  - put: docker-hub
    params: {build: source}

